---
Name: FlexSlider
---
SlideImage:
  db:
    Name: Text
    Description: Text
    SortOrder: Int
    ShowSlide: Boolean
  has_one:
    Image: Image
    Page: Page
    PageLink: SiteTree
  singular_name:
    - Slide
  plural_name:
    - Slides
  default_order:
    - SortOrder
  summary_fields:
    Name: Caption
    GridThumb: Image